# Generated by Django 5.2.4 on 2025-07-16 05:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('prix_depart', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='voitures/')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enchere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_actuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('duree_minutes', models.PositiveIntegerField(default=10)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encheres_gagnees', to=settings.AUTH_USER_MODEL)),
                ('meilleur_offreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encheres_meilleures', to=settings.AUTH_USER_MODEL)),
                ('voiture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encheres.voiture')),
            ],
        ),
    ]
