# Generated by Django 5.2.4 on 2025-07-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encheres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='image',
            field=models.ImageField(default='voitures/default.jpg', upload_to='voitures/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_offre', models.DateTimeField(auto_now_add=True)),
                ('enchere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encheres.enchere')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
