# Generated by Django 5.2.4 on 2025-07-13 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encheres', '0002_enchere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enchere',
            name='date_fin',
        ),
    ]
