# Generated by Django 5.2.4 on 2025-07-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encheres', '0003_remove_enchere_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='enchere',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
