# Generated by Django 5.2.4 on 2025-07-13 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encheres', '0004_enchere_duree_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enchere',
            name='gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encheres_gagnees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enchere',
            name='meilleur_offreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encheres_meilleures', to=settings.AUTH_USER_MODEL),
        ),
    ]
