# Generated by Django 5.2.4 on 2025-07-13 20:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encheres', '0005_enchere_gagnant_alter_enchere_meilleur_offreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enchere',
            name='prix_actuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
