# Generated by Django 5.2.4 on 2025-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encheres', '0006_alter_enchere_prix_actuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='enchere',
            name='notification_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
